<?php
/**
 * License Keys admin page template
 *
 * @package    VD_License_Manager
 * @subpackage VD_License_Manager/admin/partials
 * @since      1.0.0
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
?>

<div class="vd-licenses-page">
    <div class="vd-page-header">
        <h2><?php esc_html_e( 'License Keys Management', 'vd-license-manager' ); ?></h2>
        <p class="description">
            <?php esc_html_e( 'View and manage license keys generated by LMfWC. Monitor license assignments, status, and customer access.', 'vd-license-manager' ); ?>
        </p>
    </div>

    <div class="vd-placeholder">
        <div class="vd-placeholder-content">
            <h3><?php esc_html_e( 'License Management Coming Soon', 'vd-license-manager' ); ?></h3>
            <p><?php esc_html_e( 'This feature will be implemented in Day 3-4 of development.', 'vd-license-manager' ); ?></p>

            <h4><?php esc_html_e( 'Planned Features:', 'vd-license-manager' ); ?></h4>
            <ul>
                <li><?php esc_html_e( 'View all license keys from LMfWC integration', 'vd-license-manager' ); ?></li>
                <li><?php esc_html_e( 'Monitor license status and expiration', 'vd-license-manager' ); ?></li>
                <li><?php esc_html_e( 'View assigned pool and account information', 'vd-license-manager' ); ?></li>
                <li><?php esc_html_e( 'Track customer access and device usage', 'vd-license-manager' ); ?></li>
                <li><?php esc_html_e( 'Manual license assignment and reassignment', 'vd-license-manager' ); ?></li>
                <li><?php esc_html_e( 'Bulk license operations', 'vd-license-manager' ); ?></li>
            </ul>

            <div class="vd-mock-buttons">
                <button type="button" class="button" disabled>
                    <?php esc_html_e( 'Sync from LMfWC', 'vd-license-manager' ); ?>
                </button>
                <button type="button" class="button" disabled>
                    <?php esc_html_e( 'Export Licenses', 'vd-license-manager' ); ?>
                </button>
                <button type="button" class="button" disabled>
                    <?php esc_html_e( 'Bulk Actions', 'vd-license-manager' ); ?>
                </button>
            </div>
        </div>

        <div class="vd-mock-table">
            <table class="wp-list-table widefat fixed striped">
                <thead>
                    <tr>
                        <th><?php esc_html_e( 'License Key', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Product', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Customer', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Pool', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Account', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Status', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Expires', 'vd-license-manager' ); ?></th>
                        <th><?php esc_html_e( 'Actions', 'vd-license-manager' ); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="8" class="no-items">
                            <?php esc_html_e( 'No licenses found. License sync will be implemented in Day 3-4.', 'vd-license-manager' ); ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="vd-lmfwc-integration">
            <h4><?php esc_html_e( 'LMfWC Integration Status', 'vd-license-manager' ); ?></h4>
            <?php if ( function_exists( 'lmfwc_get_license' ) ) : ?>
                <p class="vd-status-ok">
                    <span class="dashicons dashicons-yes-alt"></span>
                    <?php esc_html_e( 'License Manager for WooCommerce is active and ready for integration.', 'vd-license-manager' ); ?>
                </p>
            <?php else : ?>
                <p class="vd-status-error">
                    <span class="dashicons dashicons-dismiss"></span>
                    <?php esc_html_e( 'License Manager for WooCommerce is not active. Please install and activate it first.', 'vd-license-manager' ); ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>